on:
  - push
  - pull_request

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error
